### ISSUE TITLE
Not detecting my VMWare CPU

### ISSUE THREAD

**Issue by alitheg** [coreos/vmw_backdoor-rs#3]
Neat library - thanks!

I ended up here having failed to boot FCOS on my ESXi system (afterburn reports it's not a VMWare CPU). I've created a new Rust project, imported this as a dependency, and tried to detect the CPU. I get "false" from the `is_vmware_cpu` function. I tried to do some more debugging but this is the very first time I've ever touched Rust! I installed cpuid and I can see that I do have the "VMwareVMware" string in my CPU info - so I can only assume (if I'm reading the code right) that it's the initial virtualization bit. 

I'm happy to keep digging if you have any pointers? Happy to accept it might be a config issue in vsphere too!

Thank you!

**Comment by lucab** [comment]
Thanks for the report! I have a suspicion about what could be wrong here, it may be a bug on my side. Can you please post the output of `cpuid -1 -l 1`? I'm interested in the `feature information (1/ecx)` part (it shouldn't contain anything privacy sensitive).

**Comment by alitheg** [comment]
Of course! See below (I've only posted 1/ecx to save you parsing the whole lot - let me know if you need the rest):

```
   feature information (1/ecx):
      PNI/SSE3: Prescott New Instructions     = true
      PCLMULDQ instruction                    = false
      64-bit debug store                      = false
      MONITOR/MWAIT                           = false
      CPL-qualified debug store               = false
      VMX: virtual machine extensions         = false
      SMX: safer mode extensions              = false
      Enhanced Intel SpeedStep Technology     = false
      thermal monitor 2                       = false
      SSSE3 extensions                        = true
      context ID: adaptive or shared L1 data  = false
      FMA instruction                         = false
      CMPXCHG16B instruction                  = true
      xTPR disable                            = false
      perfmon and debug                       = false
      process context identifiers             = false
      direct cache access                     = false
      SSE4.1 extensions                       = true
      SSE4.2 extensions                       = false
      extended xAPIC support                  = true
      MOVBE instruction                       = false
      POPCNT instruction                      = false
      time stamp counter deadline             = true
      AES instruction                         = false
      XSAVE/XSTOR states                      = false
      OS-enabled XSAVE/XSTOR                  = false
      AVX: advanced vector extensions         = false
      F16C half-precision convert instruction = false
      RDRAND instruction                      = false
      hypervisor guest status                 = true
```

**Comment by lucab** [comment]
Yes, this confirms it. I had a silly typo in the bitmask (`0x0800_0000` instead of `0x8000_0000`) which means that the code is mistakenly checking this value:
> OS-enabled XSAVE/XSTOR                  = false

https://github.com/lucab/vmw_backdoor-rs/pull/4 fixes this.

**Comment by alitheg** [comment]
Nice! Thanks @lucab!

**Comment by alitheg** [comment]
Out of interest - how long does it usually take for changes down here to make it into Afterburn and then from there into FCOS?

**Comment by alitheg** [comment]
Ah, you've already added the issue! I'll watch it there :)
